# Configurações locais de desenvolvimento
# Renomear para application-local.properties e adicionar no .gitignore

spring.datasource.url=jdbc:postgresql://localhost:5432/db_sales
spring.datasource.username=postgres
spring.datasource.password=seu_password_aqui
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/sales-api
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.example.sales=DEBUG
